name: Release

env:
  TZ: Asia/Shanghai

on:
  push:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - "steamDESC.txt"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run integration script
        run: ./main.bat

      - name: Upload generated files
        uses: actions/upload-artifact@v3
        with:
          name: font-artifact
          path: |
            *.zip

  nightly-release:
    permissions: write-all
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/') != true
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: font-artifact

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-release"
          prerelease: true
          title: "Action Build"
          files: |
            *.zip

  release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: font-artifact

      - name: Release Action
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
          body_path: CHANGELOG.md
